const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Behaviors.Follow,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Platform.Exps.GravityAngle,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetLayerEffectEnabled,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Audio.Acts.Seek,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Spritefont2.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Spritefont2.Cnds.IsRunningTypewriterText,
		C3.Plugins.Spritefont2.Acts.AddInstanceVar,
		C3.Plugins.Spritefont2.Acts.TypewriterFinish,
		C3.Behaviors.Platform.Acts.SetGravityAngle,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Behaviors.Follow.Cnds.IsPaused,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Follow.Acts.SetPaused,
		C3.Plugins.Spritefont2.Acts.SetBoolInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.Spritefont2.Acts.SubInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Audio: 0},
	{Array: 0},
	{Browser: 0},
	{GravityButton: 0},
	{JumpButton: 0},
	{LeftButton: 0},
	{RightButton: 0},
	{ShootButton: 0},
	{PauseButton: 0},
	{KraskopusHealthBar: 0},
	{Tween: 0},
	{Sine: 0},
	{EdgarSpiderHealthBar: 0},
	{LifeNumber: 0},
	{PlayerLife: 0},
	{CoinsText: 0},
	{Coins: 0},
	{CoinUI: 0},
	{LevelText: 0},
	{Talkbackground: 0},
	{NPCType: 0},
	{TalkImage: 0},
	{TalkerName: 0},
	{Clicklevel: 0},
	{Clickable: 0},
	{TalkText: 0},
	{Solid: 0},
	{Box: 0},
	{Coin: 0},
	{Gate: 0},
	{StoneBackground: 0},
	{MoveTo: 0},
	{StoneGround: 0},
	{Gravity_Down: 0},
	{Cutscene: 0},
	{Lives: 0},
	{MoveRight: 0},
	{Platform: 0},
	{Flash: 0},
	{Leon: 0},
	{Spike: 0},
	{WinArea: 0},
	{Lever: 0},
	{TalkedTo: 0},
	{NPCS: 0},
	{Follow: 0},
	{TamaraFollow: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{WatcherBubble: 0},
	{Attack: 0},
	{Attacking: 0},
	{Health: 0},
	{TheWatcherBody: 0},
	{EyeNumber: 0},
	{WatcherEye: 0},
	{Grass: 0},
	{Sky: 0},
	{DestroyGround: 0},
	{GlassWall: 0},
	{GlitchChase: 0},
	{Skull: 0},
	{GasterBody: 0},
	{Glitching: 0},
	{Side: 0},
	{GasterHead: 0},
	{GasterBubble: 0},
	{IsAttacking: 0},
	{EdgarSpider: 0},
	{LongArmAttack: 0},
	{EdgarFaceShooter: 0},
	{EdgarFaceBubble: 0},
	{MassiveEdgarHand: 0},
	{Bound: 0},
	{Triggered: 0},
	{TriggerLevel: 0},
	{Trigger: 0},
	{TeleportingPortal: 0},
	{TeleporterPortal: 0},
	{Outside: 0},
	{GreyBackground: 0},
	{ButtonType: 0},
	{PlayButton: 0},
	{TheGlitchName: 0},
	{SongNumber: 0},
	{SongText: 0},
	{Characters: 0},
	{Buttons: 0},
	{Level: 0},
	{Mobile: 0},
	{LevelNumber: 0},
	{FoughtEdgarSpider: 0},
	{Character: 0},
	{Image: 0},
	{Text: 0},
	{Speed: 0},
	{Red: 0},
	{Green: 0},
	{Blue: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	GravityButton: class extends self.ISpriteInstance {},
	JumpButton: class extends self.ISpriteInstance {},
	LeftButton: class extends self.ISpriteInstance {},
	RightButton: class extends self.ISpriteInstance {},
	ShootButton: class extends self.ISpriteInstance {},
	PauseButton: class extends self.ISpriteInstance {},
	KraskopusHealthBar: class extends self.ISpriteInstance {},
	EdgarSpiderHealthBar: class extends self.ISpriteInstance {},
	PlayerLife: class extends self.ISpriteInstance {},
	CoinsText: class extends self.ISpriteFontInstance {},
	CoinUI: class extends self.ISpriteInstance {},
	LevelText: class extends self.ISpriteFontInstance {},
	Talkbackground: class extends self.ISpriteInstance {},
	TalkImage: class extends self.ISpriteInstance {},
	TalkerName: class extends self.ISpriteFontInstance {},
	TalkText: class extends self.ISpriteFontInstance {},
	Box: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	Gate: class extends self.ISpriteInstance {},
	StoneBackground: class extends self.ITiledBackgroundInstance {},
	StoneGround: class extends self.ITiledBackgroundInstance {},
	Leon: class extends self.ISpriteInstance {},
	Spike: class extends self.ISpriteInstance {},
	WinArea: class extends self.ISpriteInstance {},
	Lever: class extends self.ISpriteInstance {},
	NPCS: class extends self.ISpriteInstance {},
	TamaraFollow: class extends self.ISpriteInstance {},
	WatcherBubble: class extends self.ISpriteInstance {},
	TheWatcherBody: class extends self.ISpriteInstance {},
	WatcherEye: class extends self.ISpriteInstance {},
	Grass: class extends self.ITiledBackgroundInstance {},
	Sky: class extends self.ITiledBackgroundInstance {},
	Bullet: class extends self.ISpriteInstance {},
	DestroyGround: class extends self.ISpriteInstance {},
	GlassWall: class extends self.ISpriteInstance {},
	GlitchChase: class extends self.ISpriteInstance {},
	Skull: class extends self.ISpriteInstance {},
	GasterBody: class extends self.ISpriteInstance {},
	GasterHead: class extends self.ISpriteInstance {},
	GasterBubble: class extends self.ISpriteInstance {},
	EdgarSpider: class extends self.ISpriteInstance {},
	LongArmAttack: class extends self.ISpriteInstance {},
	EdgarFaceShooter: class extends self.ISpriteInstance {},
	EdgarFaceBubble: class extends self.ISpriteInstance {},
	MassiveEdgarHand: class extends self.ISpriteInstance {},
	Bound: class extends self.ISpriteInstance {},
	Trigger: class extends self.ISpriteInstance {},
	TeleportingPortal: class extends self.ISpriteInstance {},
	TeleporterPortal: class extends self.ISpriteInstance {},
	GreyBackground: class extends self.ISpriteInstance {},
	PlayButton: class extends self.ISpriteInstance {},
	TheGlitchName: class extends self.ISpriteInstance {},
	SongText: class extends self.ISpriteFontInstance {},
	Characters: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {}
}